default_language_version:
  # default language version for each language used in the repository
  python: python3.11
repos:
- repo: https://github.com/ecugol/pre-commit-hooks-django
rev: v0.4.0  # Use the ref you want to point at
    hooks:
        - id: check-untracked-migrations
            # Optional, if specified, hook will work only on these branches
            # otherwise it will work on all branches
            args: ["--branches", "main", "other_branch"]
        -   id: check-unapplied-migrations
        -   id: check-absent-migrations
        -   id: po-location-format
            # Mandatory, select one of the following options:
            # file: show only the file path as location
            # never: remove all locations
            args: ["--add-location", "file"]

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
    - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
        hooks:
        # See https://pre-commit.com/hooks.html for more hooks
        - id: check-ast
        - id: check-case-conflict
        - id: check-executables-have-shebangs
        - id: check-merge-conflict
        - id: debug-statements
        - id: end-of-file-fixer
        - id: name-tests-test
            args: [ "--django" ]
        - id: trailing-whitespace
    - repo: https://github.com/asottile/seed-isort-config
        rev: v2.2.0
        hooks:
        - id: seed-isort-config
    - repo: https://github.com/pycqa/isort
        rev: 5.7.0
        hooks:
        - id: isort
    - repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        - id: black
    - repo: https://github.com/pycqa/bandit
        rev: 1.7.0
        hooks:
        - id: bandit
            args: [ "-iii", "-ll" ]
    - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
        - id: flake8
            additional_dependencies: [
                "flake8-bugbear",
                "flake8-comprehensions",
                "flake8-mutable",
                "flake8-print",
                "flake8-simplify",
            ]
    - repo: https://github.com/pycqa/pylint
        rev: "pylint-2.16.1"
        hooks:
        - id: pylint
            exclude: "[a-zA-Z]*/(migrations)/(.)*"
            args: [ "--load-plugins=pylint_django", "--django-settings-module=app.settings" ]
            additional_dependencies: [
                # pylint dependency
                pylint_django,
                # runtime dependencies
                # ...
            ]
