# Generated by Django 5.1 on 2024-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
