# Generated by Django 4.1.6 on 2023-02-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blogcomment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-post_date"],
                "permissions": [("can_publish", "Can publish Blog posts")],
            },
        ),
        migrations.AlterModelOptions(
            name="blogcomment",
            options={
                "ordering": (["-post_date"],),
                "permissions": [("can_comment", "Can publish a comment")],
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="name",
            field=models.CharField(max_length=15, verbose_name="title"),
        ),
    ]
